<a href="https://colab.research.google.com/github/HendricoYehezky/Tugas-3-Modern-Convolutional-Neural-Network/blob/main/8_4_Recurrent_Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install --upgrade tensorflow

     |████████████████████████████████| 462 kB 3.9 MB/s 


In [1]:
!pip install d2l

In [2]:
import tensorflow as tf
from d2l import tensorflow as d2l

X, W_xh = tf.random.normal((3, 1), 0, 1), tf.random.normal((1, 4), 0, 1)
H, W_hh = tf.random.normal((3, 4), 0, 1), tf.random.normal((4, 4), 0, 1)
tf.matmul(X, W_xh) + tf.matmul(H, W_hh)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.8163134 ,  1.8677897 ,  0.19883864,  1.2113019 ],
       [-1.9156806 , -0.5988319 , -2.3410807 , -0.8758656 ],
       [-0.8801456 ,  1.6501788 ,  0.631127  ,  0.45776573]],
      dtype=float32)>

In [3]:
tf.matmul(tf.concat((X, H), 1), tf.concat((W_xh, W_hh), 0))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.8163134 ,  1.8677897 ,  0.19883862,  1.2113019 ],
       [-1.9156806 , -0.59883183, -2.3410804 , -0.8758655 ],
       [-0.8801456 ,  1.6501789 ,  0.6311271 ,  0.45776576]],
      dtype=float32)>